/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.forms;

import com.db.DataAccess;
import com.db.RowData;
import com.db.Utility;
import java.io.File;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author Administrator
 */
public class BusBookingForm extends javax.swing.JFrame {

    DataAccess db=new DataAccess();
    File file;
    String cols[]=new String [] {
                "ID", "BusNo", "ScheduledDate", "Route From", "Route To", "Time Up", "Fare", "Driver", "Conductor"
            };
    
    DefaultTableModel dt;
    double fare2=0;
    String routeid="";
    String busno="";
    String id1;
    int seatno1;
    /**
     * Creates new form ItemForm
     */
    public BusBookingForm() {
        
        initComponents();
//        ResultSet rs1 = db.getRows("select * from BusRouteView");
//        System.out.println(rs1.get);
        System.out.println(Utility.getCurrentDateF("dd-MM-yyyy"));
        dt=(DefaultTableModel)table2.getModel();
        db.fillTable(table1, "select * from BusRouteView");        
        db.fillCombo(cmbid, "select * from RouteInfo", "Id", "Id");
        getContentPane().setBackground(new java.awt.Color(255,255,255));
        Utility.setLabelImage(lbl2, new File("src/images/bus2.jpg").getAbsolutePath());
        
        db.fillCombo(cmbstart, "select Distinct RouteFrom from RouteInfo", "RouteFrom", "RouteFrom");
        db.fillCombo(cmbend, "select Distinct RouteTo from RouteInfo", "RouteTo", "RouteTo");
        
        txtbdate.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
              String bdate=txtbdate.getText();
              if(bdate.equals("")){
               lblerror.setText("Booking Date cannot be left empty");
               return false;
               }else{
                  return true;
              }
            }
                        
        });
        
        txtbdate.setDate(LocalDate.now());
        txtjdate.setDate(LocalDate.now());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        txtbdate = new com.github.lgooddatepicker.components.DatePicker();
        cmbid = new javax.swing.JComboBox<>();
        txtfare = new javax.swing.JTextField();
        lblinfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        lblerror = new javax.swing.JLabel();
        btnfare = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtjdate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbstart = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbend = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtsdate2 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel17 = new javax.swing.JLabel();
        btnbrowse1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Information");
        setBackground(new java.awt.Color(227, 134, 21));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Ticket No");
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtid.setEditable(false);
        txtid.setText("[AUTO]");
        txtid.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel2.setText("Bus No");
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel4.setText("Total Fare");
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel5.setText("Booking Date");
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-as-icon.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reset2_32x32.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        cmbid.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbidItemStateChanged(evt);
            }
        });

        txtfare.setEditable(false);
        txtfare.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblinfo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SeatNo", "Name", "Age", "Gender"
            }
        ));
        jScrollPane1.setViewportView(table2);

        jLabel3.setText("Personal Details::");
        jLabel3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        btnadd.setText("Add Row");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndel.setText("Delete Row");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        lblerror.setBackground(new java.awt.Color(204, 255, 204));
        lblerror.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblerror.setForeground(new java.awt.Color(255, 0, 0));
        lblerror.setOpaque(true);

        btnfare.setText("Calculate Fare");
        btnfare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfareActionPerformed(evt);
            }
        });

        jLabel6.setText("Journey Date");
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Select Route ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnsave)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnreset))
                                .addComponent(lblerror, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(6, 6, 6)
                                .addComponent(txtjdate, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnadd)
                                        .addGap(18, 18, 18)
                                        .addComponent(btndel)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnfare))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5))
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(cmbid, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtfare, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtfare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btndel)
                        .addComponent(btnfare))
                    .addComponent(btnadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblerror, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnreset))
                .addContainerGap())
        );

        jLabel10.setText("From:");
        jLabel10.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        cmbstart.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ScheduledDate", "ID", "BusNo", "Bus Type", "Seats", "Avail Seats", "Reserved", "Route From", "Route To", "Time Up", "Fare", "Driver", "Conductor"
            }
        ));
        table1.setRowHeight(40);
        jScrollPane2.setViewportView(table1);

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditContact_32x32.png"))); // NOI18N
        btnedit.setText("Select Bus");
        btnedit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));

        jLabel11.setText("Search Bus for Booking");
        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        btnclose.setText("X");
        btnclose.setBackground(new java.awt.Color(153, 153, 255));
        btnclose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnclose.setContentAreaFilled(false);
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jLabel19.setText("Bus Booking/Ticket Booking Form");
        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(476, 476, 476)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(864, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jLabel11)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel19)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        jLabel15.setText("To");
        jLabel15.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        cmbend.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel16.setText("Date");
        jLabel16.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        jLabel17.setText("(Optional)");
        jLabel17.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N

        btnbrowse1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search-Images-icon.png"))); // NOI18N
        btnbrowse1.setText("Search");
        btnbrowse1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowse1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Search Bus");
        jLabel18.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbstart, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbend, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbrowse1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnedit)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cmbend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(txtsdate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(btnbrowse1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnedit)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        try {
            // Save
            
            String id=txtid.getText();
            String bdate=txtbdate.getDate().format(DateTimeFormatter.ISO_DATE);
            String jdate=txtjdate.getDate().format(DateTimeFormatter.ISO_DATE);
            String tfare=txtfare.getText();
            
           
            
            
            
            
            if (bdate.compareTo(Utility.getCurrentDate()) < 0)
            {
                JOptionPane.showMessageDialog(this, "INVALID BOOKING DATE SELECTION");
                return;
            }
            
            if(txtbdate.getDate().compareTo(txtjdate.getDate())>0)
            {
                JOptionPane.showMessageDialog(this, "Journery Date must be equal to greater than booking date");
                return;
            }
            System.out.println(txtbdate.getDate());
            ResultSet rs2=db.getRows("select * from BusRouteView where Id=?",id1 );
            rs2.next();
            int rsv = Integer.parseInt(rs2.getString("ASeats"));
            seatno1 = Integer.parseInt(rs2.getString("Seats"));
            
            
            
            if(rsv <= 0)
            {
                JOptionPane.showMessageDialog(this, "RESERVATION FULL");
                return;
            }
            
//        if(txtbdate.getDate().compareTo(Utility.getCurrentDate())>0)
//        {
//            JOptionPane.showMessageDialog(this, "Journery Date must be equal to greater than booking date");
//            return;
//        }


int tkno=db.executeId("Insert into Booking (BookingDate,JourneyDate,RouteId,TotalFare) values(?,?,?,?)", bdate,jdate,routeid,tfare);
for(int i=0;i<table2.getRowCount();i++)
{
    String seatno=table2.getValueAt(i, 0)+"";
    String name=table2.getValueAt(i, 1)+"";
    String age=table2.getValueAt(i, 2)+"";
    String gender=table2.getValueAt(i, 3)+"";
    if (Integer.parseInt(seatno) > seatno1 )
    {
        JOptionPane.showMessageDialog(this,"Seat Number outOf range");
        return;
    }
    db.execute("Insert into BookingDetails values(?,?,?,?,?)", tkno+"",seatno,name,age,gender);            
}

           
db.execute("Update Bus set ASeats=ASeats-"+table2.getRowCount()+",Reserved=Seats-ASeats where BusNo='"+busno+"'");

JOptionPane.showMessageDialog(this, "Booking Done Successfully");
db.fillTable(table1, "select * from BusRouteView");
btnreset.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(BusBookingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // Reset
        txtid.setText("[AUTO]");
        lblinfo.setText("");        
        txtbdate.setText("");
        txtjdate.setText("");
        txtfare.setText("");
        dt.setRowCount(0);
        txtbdate.requestFocus();        
    }//GEN-LAST:event_btnresetActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // Edit
        int rowindex=table1.getSelectedRow();
        if(rowindex!=-1)
        {
        String id=table1.getValueAt(rowindex, 1)+"";
        edit(id);   
        id1=id;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error:::Please select row to Edit...");
        }
    }//GEN-LAST:event_btneditActionPerformed
    void edit(String id)
    {
        try {
            
            
            ResultSet rs=db.getRows("select * from BusRouteView where Id=?", id);
            if(rs.next())
            {
                routeid=rs.getString(2);
                busno=rs.getString(3);
                String sdate=rs.getString(1);
                String from=rs.getString(8);
                String to=rs.getString(9);
                String time=rs.getString(10);
                
                String str="<html>Bus No -"+busno+" Date - "+sdate+"<br>From - "+from+" To - "+to+" Time - "+time;
                fare2=rs.getDouble(11);
                
                lblinfo.setText(str);                
                txtjdate.setDate(LocalDate.parse(sdate));
                txtbdate.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(BusBookingForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void cmbidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbidItemStateChanged
        String id=((RowData)cmbid.getSelectedItem()).value;
        edit(id);
    }//GEN-LAST:event_cmbidItemStateChanged

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnbrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowse1ActionPerformed
        String sql="select * from BusRouteView where RouteFrom='"+cmbstart.getSelectedItem()+"' and RouteTo='"+cmbend.getSelectedItem()+"'";
        if(!txtsdate2.getText().equals(""))
        {
            String sdate=txtsdate2.getDate().format(DateTimeFormatter.ISO_DATE);
            sql=sql+" and Scheduleddate='"+sdate+"'";            
        }
        db.fillTable(table1, sql);
    }//GEN-LAST:event_btnbrowse1ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        dt.addRow(new Object[]{"","","",""});
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        int i=table2.getSelectedRow();
        if(i!=-1)
        {
            dt.removeRow(i);
            btnfare.doClick();
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void btnfareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfareActionPerformed
        double fare=0;
        for(int i=0;i<table2.getRowCount();i++)
        {
            int age=Integer.parseInt(table2.getValueAt(i, 2).toString());
            if(age>=3 && age<=5)
            {
                fare+=(fare2/2);
            }
            else
            {
                fare+=fare2;
            }
            txtfare.setText(fare+"");
        }
    }//GEN-LAST:event_btnfareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusBookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusBookingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnbrowse1;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnfare;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbend;
    private javax.swing.JComboBox<String> cmbid;
    private javax.swing.JComboBox<String> cmbstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lblinfo;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private com.github.lgooddatepicker.components.DatePicker txtbdate;
    private javax.swing.JTextField txtfare;
    private javax.swing.JTextField txtid;
    private com.github.lgooddatepicker.components.DatePicker txtjdate;
    private com.github.lgooddatepicker.components.DatePicker txtsdate2;
    // End of variables declaration//GEN-END:variables
}
