/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.forms;

import com.db.DataAccess;
import com.db.Utility;
import com.mysql.jdbc.Util;
import java.awt.Color;
import java.awt.Container;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class ChangePasswordForm extends javax.swing.JFrame {

    static DataAccess db=new DataAccess();
    //only static members we can access in static method
    /**
     * Creates new form LoginForm
     */
    public ChangePasswordForm() {
        
        initComponents();
        Container c=getContentPane();     
        c.setBackground(new Color(255, 255, 102));        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnewpass2 = new javax.swing.JPasswordField();
        btnlogin = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtnewpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 0, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Change Password Form");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 610, 69);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Confirm New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 160, 160, 30);

        txtnewpass2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtnewpass2.setForeground(new java.awt.Color(153, 0, 0));
        txtnewpass2.setToolTipText("Enter Valid Password");
        txtnewpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewpass2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtnewpass2);
        txtnewpass2.setBounds(330, 150, 250, 30);

        btnlogin.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        btnlogin.setText("Submit");
        btnlogin.setToolTipText("Login to Hardware Shop App");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(330, 200, 130, 40);

        btncancel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Close_32x32.png"))); // NOI18N
        btncancel.setText("Cancel");
        btncancel.setToolTipText("Cancel Login Form and Exit from System");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(460, 200, 120, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employeesIcon200.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 110, 104, 100);

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtpass.setForeground(new java.awt.Color(153, 0, 0));
        txtpass.setToolTipText("Enter Valid Password");
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass);
        txtpass.setBounds(330, 90, 250, 30);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("New Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 130, 94, 16);

        txtnewpass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtnewpass.setForeground(new java.awt.Color(153, 0, 0));
        txtnewpass.setToolTipText("Enter Valid Password");
        txtnewpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnewpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtnewpass);
        txtnewpass.setBounds(330, 120, 250, 30);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Old Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 100, 87, 16);

        setSize(new java.awt.Dimension(606, 267));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
            String oldpass=txtpass.getText();
            String newpass=txtnewpass.getText();
            String newpass2=txtnewpass2.getText();
            if(oldpass.equals("") || newpass.equals("") || newpass2.equals(""))
            {
                JOptionPane.showMessageDialog(this, "All fields are required");
                return;
            }
            if(!oldpass.equals(MainForm.userPass))
            {
                JOptionPane.showMessageDialog(this, "Old Password is wrong.. try again");
                txtpass.requestFocus();
                return;
            }
            if(!newpass.equals(newpass2))
            {
                JOptionPane.showMessageDialog(this, "New and confirm new password mistmatch.. try again");
                txtnewpass2.requestFocus();
                return;
            }
            db.execute("Update Login set Password=? where UserName=? and Password=?", newpass, MainForm.user,oldpass);
            JOptionPane.showMessageDialog(this, "Your Password changed Successfully");
            
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtnewpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewpass2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewpass2ActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtnewpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnewpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnewpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordForm().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField txtnewpass;
    private javax.swing.JPasswordField txtnewpass2;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
