/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.forms;

import com.db.DataAccess;
import com.db.RowData;
import com.db.Utility;
import java.io.File;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class EmployeeForm extends javax.swing.JFrame {

    DataAccess db=new DataAccess();
    File file;
    String cols[]=new String [] {
                "Employee ID", "Employeer Name", "Address", "Birth Date", "Joining Date", "Contact No", "EmailID", "Designation", "Photo"
            };
    /**
     * Creates new form ItemForm
     */
    public EmployeeForm() {
        
        initComponents();
        db.fillTable(table1, "select * from Employee",8,cols);
        db.enableSearch(cmbfield,txtsearch, table1, "select * from Employee",8,cols);   
        db.fillCombo(cmbempno, "select * from Employee", "EmpNo", "EmpNo");
        //Utility.setBackgroundImage(this, new File("src/images/bus2.jpg").getAbsolutePath());
        getContentPane().setBackground(new java.awt.Color(255,255,255));
        Utility.setLabelImage(lbl2, new File("src/images/employeesIcon200.jpg").getAbsolutePath());
        
        txtname.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
              String name=txtname.getText();
              if(name.equals("")){
               lblerror.setText("Name cannot be left empty");
               return false;
               }else{
                  if(name.matches("^[a-zA-Z ]+$")){  // ^RegExPattern$
                  lblerror.setText("");
                  return true;
                  }else{
                      lblerror.setText("Name allows only letters and spaces");
                      return false;
                  }
              }
            }
        });
        
        txtcontact.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String mobile=txtcontact.getText();
                if(mobile.equals("")){
                    lblerror.setText("Mobile No is required");
                    return false;
                }else{
                    if(mobile.matches("^[0-9]{10}$")){
                        lblerror.setText("");
                        return true;
                    }else{
                        lblerror.setText("Mobile No must be of 10 digits");
                        return false;
                    }
                }
                        
            }
        });
        txtemail.setInputVerifier(new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                String email=txtemail.getText();
                if(email.equals("")){
                    lblerror.setText("Email ID is required");
                    return false;
                }else{
                    if(email.matches("^\\w+@\\w+\\.\\w{2,3}(\\.\\w{2,3})?$")){
                        lblerror.setText("");
                        return true;
                    }else{
                        lblerror.setText("Invalid format of Email ID");
                        return false;
                    }
                }
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnsave = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        txtcontact = new javax.swing.JTextField();
        txtbdate = new com.github.lgooddatepicker.components.DatePicker();
        cmbdesg = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtjdate = new com.github.lgooddatepicker.components.DatePicker();
        jLabel9 = new javax.swing.JLabel();
        lblphoto = new javax.swing.JLabel();
        btnbrowse = new javax.swing.JButton();
        cmbempno = new javax.swing.JComboBox<>();
        btnnew = new javax.swing.JButton();
        lblerror = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbfield = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee Information");
        setBackground(new java.awt.Color(227, 134, 21));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Employee ID");
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtid.setEditable(false);
        txtid.setText("[AUTO]");
        txtid.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel2.setText("Employee Name");
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel3.setText("Employee Address");
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtaddress.setColumns(20);
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        jLabel4.setText("Contact/Mobile No");
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel5.setText("Birth Date");
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel6.setText("Email ID");
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtemail.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel7.setText("Designation");
        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-as-icon.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reset2_32x32.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        txtcontact.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        cmbdesg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driver", "Conductor", "Manager", "Clerk", "Accountant", " " }));
        cmbdesg.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbdesg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdesgActionPerformed(evt);
            }
        });

        jLabel8.setText("Joining Date");
        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel9.setText("Employee Image");
        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        lblphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnbrowse.setText("Browse");
        btnbrowse.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });

        cmbempno.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbempno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbempnoItemStateChanged(evt);
            }
        });
        cmbempno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbempnoActionPerformed(evt);
            }
        });

        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Notes_32x32.png"))); // NOI18N
        btnnew.setText("New");
        btnnew.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        lblerror.setBackground(new java.awt.Color(204, 255, 204));
        lblerror.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblerror.setForeground(new java.awt.Color(255, 0, 0));
        lblerror.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnbrowse)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcontact, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnnew)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnsave)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnreset))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtbdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cmbempno, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(cmbdesg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbempno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtjdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbdesg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbrowse)))
                .addGap(11, 11, 11)
                .addComponent(lblerror, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btnreset)
                    .addComponent(btnnew))
                .addContainerGap())
        );

        jLabel10.setText("Search");
        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        cmbfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EmpNo", "EmpName", "EmpAddress", "BirthDate", "JoinDate", "Designation" }));
        cmbfield.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtsearch.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employeer Name", "Address", "Birth Date", "Joining Date", "Contact No", "EmailID", "Designation", "Photo"
            }
        ));
        table1.setRowHeight(40);
        jScrollPane2.setViewportView(table1);

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EditContact_32x32.png"))); // NOI18N
        btnedit.setText("Edit Employee");
        btnedit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_32x32.png"))); // NOI18N
        btndelete.setText("Delete Employee");
        btndelete.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Print_32x32.png"))); // NOI18N
        btnprint.setText("Print");
        btnprint.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));

        jLabel11.setText("Employee Details Form");
        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        btnclose.setText("X");
        btnclose.setBackground(new java.awt.Color(153, 153, 255));
        btnclose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnclose.setContentAreaFilled(false);
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 685, Short.MAX_VALUE)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(cmbfield, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnedit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btndelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnprint)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndelete)
                            .addComponent(btnedit)
                            .addComponent(btnprint))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // Save      
        if(txtbdate.getText().equals(""))
        {
            lblerror.setText("Birth Date is Required");
            txtbdate.requestFocus();
            return;
        }
        if(txtjdate.getText().equals(""))
        {
            lblerror.setText("Join Date is Required");
            txtjdate.requestFocus();
            return;
        }
        String id=txtid.getText();
        String name=txtname.getText();
        String address=txtaddress.getText();        
        String bdate=txtbdate.getDate().format(DateTimeFormatter.ISO_DATE);
        String jdate=txtjdate.getDate().format(DateTimeFormatter.ISO_DATE);
        String contact=txtcontact.getText();
        String email=txtemail.getText();
        String desg=cmbdesg.getSelectedItem()+"";
        
        String btntext=btnsave.getText().toLowerCase();
        if(btntext.equals("save"))
        {
            if(file==null)
            {
                lblerror.setText("Employee Image is Required");
                return;
            }
            db.execute("Insert into Employee (EmpName,EmpAddress,BirthDate,JoinDate,ContactNo,EmailId,Designation,Photo) values(?,?,?,?,?,?,?,?)",8,file, name,address,bdate,jdate,contact,email,desg,"");
            JOptionPane.showMessageDialog(this, "Employee is Saved Successfully");            
        }
        else
        {
            db.execute("Update Employee set EmpName=?,EmpAddress=?,BirthDate=?,JoinDate=?,ContactNo=?,EmailId=?,Designation=?,Photo=? where EmpNo=?",8,file,name,address,bdate,jdate,contact,email,desg,"",id);            
            JOptionPane.showMessageDialog(this, "Employee is Updated Successfully");
        }
        db.fillTable(table1, "select * from Employee",8,cols); 
        db.fillCombo(cmbempno, "select * from Employee", "EmpNo", "EmpNo");
        btnreset.doClick();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // Reset
        txtid.setText("[AUTO]");
        txtname.setText("");
        txtaddress.setText("");
        txtbdate.setText("");
        txtjdate.setText("");
        txtcontact.setText("");        
        txtemail.setText("");
        cmbdesg.setSelectedIndex(-1);
        lblphoto.setIcon(null);
        btnsave.setText("Save");
        txtname.requestFocus();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // Edit
        int rowindex=table1.getSelectedRow();
        if(rowindex!=-1)
        {
        String id=table1.getValueAt(rowindex, 0)+"";
        edit(id);        
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error:::Please select row which you have to edit...");
        }
    }//GEN-LAST:event_btneditActionPerformed
    void edit(String id)
    {
        try {
            
            
            ResultSet rs=db.getRows("select * from Employee where EmpNo=?", id);
            if(rs.next())
            {
                String name=rs.getString(2);
                String address=rs.getString(3);
                String bdate=rs.getString(4);
                String jdate=rs.getString(5);
                String contact=rs.getString(6);
                String email=rs.getString(7);
                String desg=rs.getString(8);
                
                txtid.setText(id);
                txtname.setText(name);
                txtaddress.setText(address);
                txtcontact.setText(contact);
                txtbdate.setDate(LocalDate.parse(bdate));
                txtjdate.setDate(LocalDate.parse(jdate));
                txtemail.setText(email);
                cmbdesg.setSelectedItem(desg); 
                InputStream in=rs.getBinaryStream(9);
                try {
                    file=Utility.getFileFromStream(in);
                } catch (Exception ex) {
                    Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                db.setImageToLabel(file, lblphoto);
                
                btnsave.setText("Update");
                txtname.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // Delete
        int val=JOptionPane.showConfirmDialog(this, "Do you want delete selected record?","Confirm Delete",JOptionPane.YES_NO_OPTION);
        if(val==JOptionPane.YES_OPTION)
        {
        int rowindex=table1.getSelectedRow();
        String id=table1.getValueAt(rowindex, 0)+"";
        db.execute("delete from Employee where EmpNo=?", id);
        db.fillTable(table1, "select * from Employee",8,cols);  
        db.fillCombo(cmbempno, "select * from Employee", "EmpNo", "EmpNo");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // Print
        File f=new File("src/reports/employee_report.jrxml");
        db.displayReport(f.getAbsolutePath());
    }//GEN-LAST:event_btnprintActionPerformed

    private void cmbdesgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdesgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdesgActionPerformed

    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
        // Browse Button
        //File f=new File();
        JFileChooser obj=new JFileChooser();
        obj.setDialogTitle("Choose Employee Image");
        int val=obj.showOpenDialog(this); //Parent
        if(val==JFileChooser.APPROVE_OPTION) //if open button selected
        {
            file=obj.getSelectedFile();
            db.setImageToLabel(file, lblphoto);
        }
    }//GEN-LAST:event_btnbrowseActionPerformed

    private void cmbempnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbempnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbempnoActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
       btnreset.doClick();
    }//GEN-LAST:event_btnnewActionPerformed

    private void cmbempnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbempnoItemStateChanged
        String id=((RowData)cmbempno.getSelectedItem()).value;
        edit(id);
    }//GEN-LAST:event_cmbempnoItemStateChanged

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbrowse;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbdesg;
    private javax.swing.JComboBox<String> cmbempno;
    private javax.swing.JComboBox<String> cmbfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JTable table1;
    private javax.swing.JTextArea txtaddress;
    private com.github.lgooddatepicker.components.DatePicker txtbdate;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private com.github.lgooddatepicker.components.DatePicker txtjdate;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
